rch_options = [('Stream Inflow (cms)', 'FLOW_INcms'),
                ('Stream Outflow (cms)', 'FLOW_OUTcms'),
                ('Evaporation (cms)', 'EVAPcms'),
                ('Transpiration Loss (cms)', 'TLOSScms'),
                ('Sediment Inflow (tons)', 'SED_INtons'),
                ('Sediment Outflow (tons)', 'SED_OUTtons'),
                ('Organic Nitrogen Inflow (kg)', 'ORGN_INkg'),
                ('Organic Nitrogen Outflow (kg)', 'ORGN_OUTkg'),
                ('Organic Phosphorus Inflow (kg)', 'ORGP_INkg'),
                ('Organic Phosphorus Outflow (kg)', 'ORGP_OUTkg'),
                ('Nitrate Inflow (kg)', 'NO3_INkg'),
                ('Nitrate Outflow (kg)', 'NO3_OUTkg'),
                ('Ammonia Inflow (kg)', 'NH4_INkg'),
                ('Ammonia Outflow (kg)', 'NH4_OUTkg'),
                ('Nitrogen Dioxide Inflow (kg)', 'NO2_INkg'),
                ('Nitrogen Dioxide Outflow (kg)', 'NO2_OUTkg'),
                ('Mineral Phosphorus Inflow (kg)', 'MINP_INkg'),
                ('Mineral Phosphorus Outflow (kg)', 'MINP_OUTkg'),
                ('Chlorophyll-a Inflow (kg)', 'CHLA_INkg'),
                ('Chlorophyll-a Outflow (kg)', 'CHLA_OUTkg'),
                ('CBOD Inflow (kg)', 'CBOD_INkg'),
                ('CBOD Outflow (kg)', 'CBOD_OUTkg'),
                ('Dissolved Oxygen Inflow (kg)', 'DISOX_INkg'),
                ('Dissolved Oxygen Outflow (kg)', 'DISOX_OUTkg'),
                ('Soluble Pesticide Inflow (mg)', 'SOLPST_INmg'),
                ('Soluble Pesticide Inflow (mg)', 'SOLPST_OUTmg'),
                ('Pesticide Sorbed to Sediment Transport Inflow (mg)','SORPST_INmg'),
                ('Pesticide Sorbed to Sediment Transport Outflow (mg)', 'SORPST_OUTmg'),
                ('Loss of Pesticide from Water by Reaction (mg)','REACTPSTmg'),
                ('Loss of Pesticide from Water by Volatilization (mg)','VOLPSTmg'),
                ('Pesticide Transfer from Water to River Bed Sediment (mg)','SETTLPSTmg'),
                ('Resuspension of Pesticide from River Bed to Water (mg)','RESUSP_PSTmg'),
                ('Diffusion of Pesticide from Water to River Bed Sediment (mg)','DIFFUSEPSTmg'),
                ('Loss of Pesticide from River Bed by Reaction (mg)','REACBEDPSTmg'),
                ('Loss of Pesticide from River Bed by Burial (mg)','BURYPSTmg'),
                ('Pesticide in River Bed Sediment (mg)','BED_PSTmg'),
                ('Persistent Bacterial Outflow (count)','BACTP_OUTct'),
                ('Less Persistent Bacterial Outflow (count)','BACTLP_OUT'),
                ('Conservative metal #1 Outflow (kg)','CMETAL#1kg'),
                ('Conservative Metal #2 Outflow (kg)','CMETAL#2kg'),
                ('Conservative Metal #3 Outflow (kg)','CMETAL#3kg'),
                ('Total Nitrogen (kg)','TOTNkg'),
                ('Total Phosphourus (kg)','TOTPkg'),
                ('Nitrate Concentration (mg/l)','NO3ConcMg/l'),
                ('Water Temperature (deg C)','WTMPdegc')
                ]



rch_param_names = {'':'', 'RCH':'Reach', 'GIS':'GIS',  'MON':'Month', 'DA':'Day', 'YR':'Year', 'AREAkm2':'Area (km2)',
               'FLOW_INcms':'Inflow (cms)', 'FLOW_OUTcms':'Outflow (cms)', 'EVAPcms':'Evaporation (cms)',
               'TLOSScms':'Transpiration Loss (cms)', 'SED_INtons':'Sediment Inflow (tons)',
               'SED_OUTtons':'Sediment Outflow (tons)',
               'SEDCONCmg/kg':'Sediment Concentration (mg/kg)', 'ORGN_INkg':'Organic Nitrogen Inflow (kg)',
               'ORGN_OUTkg':'Organic Nitrogen Outflow (kg)', 'ORGP_INkg':'Organic Phosphorus Inflow (kg)',
               'ORGP_OUTkg':'Organic Phosphorus Outflow (kg)', 'NO3_INkg':'Nitrate Inflow (kg)',
               'NO3_OUTkg':'Nitrate Outflow (kg)',
               'NH4_INkg':'Ammonia Inflow (kg)', 'NH4_OUTkg': 'Ammonia Outflow (kg)',
               'NO2_INkg': 'Nitrogen Dioxide Inflow (kg)',
               'NO2_OUTkg': 'Nitrogen Dioxide Outflow (kg)', 'MINP_INkg':'Mineral Phosphorus Inflow (kg)',
               'MINP_OUTkg':'Mineral Phosphorus Outflow (kg)', 'CHLA_INkg':'Chlorophyll-a Inflow (kg)',
               'CHLA_OUTkg': 'Chlorophyll-a Outflow (kg)',
               'CBOD_INkg':'Carbonaceous BOD Inflow (kg)','CBOD_OUTkg': 'Carbonaceous BOD Outflow (kg)',
               'DISOX_INkg': 'Dissolved Oxygen Inflow (kg)', 'DISOX_OUTkg': 'Dissolved Oxygen Outflow (kg)',
               'SOLPST_INmg': 'Soluble Pesticide Inflow (mg)', 'SOLPST_OUTmg':'Soluble Pesticide Outflow (mg)',
               'SORPST_INmg':'Pesticide Sorbed to Sediment Transport Inflow (mg)',
               'SORPST_OUTmg':'Pesticide Sorbed to Sediment Transport Outflow (mg)',
               'REACTPSTmg':'Loss of Pesticide from Water by Reaction (mg)',
               'VOLPSTmg':'Loss of Pesticide from Water by Volatilization (mg)',
               'SETTLPSTmg':'Pesticide Transfer from Water to River Bed Sediment (mg)',
               'RESUSP_PSTmg':'Resuspension of Pesticide from River Bed to Water (mg)',
               'DIFFUSEPSTmg':'Diffusion of Pesticide from Water to River Bed Sediment (mg)',
               'REACBEDPSTmg':'Loss of Pesticide from River Bed by Reaction (mg)',
               'BURYPSTmg':'Loss of Pesticide from River Bed by Burial (mg)',
               'BED_PSTmg':'Pesticide in River Bed Sediment (mg)', 'BACTP_OUTct':'Persistent Bacterial Outflow (count)',
               'BACTLP_OUT':'Less Persistent Bacterial Outflow (count)',
               'CMETAL#1kg':'Conservative metal #1 Outflow (kg)',
               'CMETAL#2kg': 'Conservative Metal #2 Outflow (kg)', 'CMETAL#3kg':'Conservative Metal #3 Outflow (kg)',
               'TOTNkg':'Total Nitrogen (kg)',
               'TOTPkg':'Total Phosphourus (kg)', 'NO3ConcMg/l':'Nitrate Concentration (mg/l)',
               'WTMPdegc':'Water Temperature (deg C)'
               }


rch_param_vals = ['', 'RCH', 'GIS', 'MON', 'AREAkm2', 'FLOW_INcms', 'FLOW_OUTcms', 'EVAPcms', 'TLOSScms', 'SED_INtons',
                  'SED_OUTtons', 'SEDCONCmg/kg', 'ORGN_INkg', 'ORGN_OUTkg', 'ORGP_INkg', 'ORGP_OUTkg', 'NO3_INkg',
                  'NO3_OUTkg', 'NH4_INkg', 'NH4_OUTkg', 'NO2_INkg', 'NO2_OUTkg', 'MINP_INkg', 'MINP_OUTkg',
                  'CHLA_INkg', 'CHLA_OUTkg', 'CBOD_INkg', 'CBOD_OUTkg', 'DISOX_INkg', 'DISOX_OUTkg', 'SOLPST_INmg',
                  'SOLPST_OUTmg', 'SORPST_INmg', 'SORPST_OUTmg', 'REACTPSTmg', 'VOLPSTmg', 'SETTLPSTmg', 'RESUSP_PSTmg',
                  'DIFFUSEPSTmg', 'REACBEDPSTmg', 'BURYPSTmg', 'BED_PSTmg', 'BACTP_OUTct', 'BACTLP_OUTct', 'CMETAL#1kg',
                  'CMETAL#2kg', 'CMETAL#3kg', 'TOTNkg', 'TOTPkg', 'NO3ConcMg/l', 'WTMPdegc']





sub_options = [('Precipitation (mm)', 'PRECIPmm'),
                ('Snow Melt (mm)', 'SNOMELTmm'),
                ('Potential Evapotranspiration (mm)', 'PETmm'),
                ('Evapotranspiration (mm)', 'ETmm'),
                ('Soil Water Content (mm)', 'SWmm'),
                ('Percolation (mm)', 'PERCmm'),
                ('Surface Runoff (mm)', 'SURQmm'),
                ('Groundwater Contribution to Streamflow (mm)', 'GW_Qmm'),
                ('Water Yield (mm)', 'WYLDmm'),
                ('Sediment Yield (tons/ha)', 'SYLDt/ha'),
                ('Organic Nitrogen (kg/ha)', 'ORGNkg/ha'),
                ('Organic Phosphorus Yield (kg/ha)', 'ORGPkg/ha'),
                ('Nitrate in Surface Runoff (kg/ha)', 'NWURQkg/ha'),
                ('Soluble Phosphorus Yield (kg/ha)', 'LOLPkg/ha'),
                ('Mineral Phosphorus Yield (kg/ha)', 'SEDPkg/ha'),
                ('Lateral Flow (mm)', 'LATQmm'),
                ('Nitrate in Lateral Flow (kg/ha)', 'LATNO3kg/ha'),
                ('Nitrate Loading in Groundwater (kg/ha)', 'GWNO3kg/ha'),
                ('Chloraphyll-a Loading (mic/L)', 'CHOLAmic/L'),
                ('Carbonaceous BOD Loading (mg/L)', 'CBODUmg/L'),
                ('Dissolved Oxygen Loading (mg/L)', 'DOXQmg/L'),
                ('Nitrate in Tile Flow (kg/ha)', 'TNO3kg/ha')
               ]


sub_param_names = {'':'', 'SUB':'Subbasin', 'GIS':'GIS',  'MO':'Month', 'DA':'Day', 'YR':'Year', 'AREAkm2':'Area (km2)',
               'PRECIPmm':'Precipitation (mm)', 'SNOMELTmm':'Snow Melt (mm)', 'PETmm':'Potential Evapotranspiration (mm)',
               'ETmm':'Evapotranspiration (mm)', 'SWmm':'Soil Water Content (mm)', 'PERCmm':'Percolation (mm)',
               'SURQmm':'Surface Runoff (mm)', 'GW_Qmm':'Groundwater Contribution to Streamflow (mm)',
               'WYLDmm':'Water Yield (mm)', 'SYLDt/ha':'Sediment Yield (tons/ha)',
               'ORGNkg/ha':'Organic Nitrogen Yield (kg/ha)', 'ORGPkg/ha':'Organic Phosphorus Yield (kg/ha)',
               'NSURQkg/ha':'Nitrate in Surface Runoff (kg/ha)', 'SOLPkg/ha':'Soluble Phosphorus Yield (kg/ha)',
               'SEDPkg/ha': 'Mineral Phosphorus Yield (kg/ha)', 'LATQmm': 'Lateral Flow (mm)',
               'LATNO3kg/ha': 'Nitrate in Lateral Flow (kg/ha)', 'GWNO3kg/ha':'Nitrate Loading in Groundwater (kg/ha)',
               'CHOLAmic/L':'Chloraphyll-a Loading (mic/L)', 'CBODUmg/L':'Carbonaceous BOD Loading (mg/L)',
               'DOXQmg/L': 'Dissolved Oxygen Loading (mg/L)', 'TNO3kg/ha': 'Nitrate in Tile Flow (kg/ha)'
               }


sub_param_vals = ['', 'SUB', 'GIS', 'MO', 'DA', 'YR', 'AREAkm2', 'PRECIPmm', 'SNOMELTmm', 'PETmm', 'ETmm', 'SWmm', 'PERCmm',
              'SURQmm', 'GW_Qmm', 'WYLDmm', 'SYLDt/ha', 'ORGNkg/ha', 'ORGPkg/ha', 'NSURQkg/ha', 'SOLPkg/ha',
              'SEDPkg/ha', 'LATQmm', 'LATNO3kg/ha', 'GWNO3kg/ha', 'CHOLAmic/L', 'CBODUmg/L', 'DOXQmg/L', 'TNO3kg/ha']